### ISSUE TITLE
Unspecified "error" event thrown

### ISSUE THREAD

**Issue by schonfeld** [dropbox/amqp-coffee#23]
Hey there.

I've been using the wrapper in prod for almost a week now, and for the most part, it's been working great.

I noticed today that every few hours, an unspecified error event is thrown from Connection.js. I've included the stack trace, and screenshots from my logs. Please, let me know if there's anything else I can provide...

Stack Trace Gist: https://gist.githubusercontent.com/schonfeld/271cf723bed2385aa02d/raw/65a18c13552ad0053482383751e44ede1185d683/gistfile1.txt

Screenshot: https://www.dropbox.com/s/gm5geyrf6pyp1mg/Screenshot%202014-08-11%2012.43.29.png

Thanks,
- Michael.

**Comment by vkfont** [comment]
have this issue at least on rabbit 3.5.0 (localhost, no network problems) and 3.4.3 (cluster)
connection is closing after {heartbeet * 3} ms, but if i'll send no more than one message in {heartbeet} ms - connection is not closing
