### ISSUE TITLE
Support channelMax and frameMax negotiation

### ISSUE THREAD

**Issue by carlhoerberg** [dropbox/amqp-coffee#29]
This library can't connect if the server has limited channelMax.

**Comment by barshow** [comment]
Ok I pushed a fix for this, it will no honor channel max and frame max BUT it doesn't enforce and channel limits from the client.  Im not sure what the correct if you try to do something when the channel limit is reached.  Do you error immediately or wait and queue things up? I think i'm leaning towards just error quickly. 

you can test it with amqp-coffee@0.1.22-rc2 

heres the commit : https://github.com/dropbox/amqp-coffee/commit/bfc9fd126de51a716d611de8cdc360d566e42e0c

**Comment by carlhoerberg** [comment]
Thanks!
