### ISSUE TITLE
tls support

### ISSUE THREAD

**Issue by AVVS** [dropbox/amqp-coffee#36]
I've been trying to integrate one, but with no success so far, main culprit is how reconnect is handled. basically what's done is called socket.connect() on a severed net socket, which reuses one, problem is that it doesnt work with tls (or I just dont know how to make it work). I wondered if it's better to abstract (re)connecting to `reconnect-core` module and setup proper handler there?

**Comment by barshow** [comment]
here is a first pass https://github.com/dropbox/amqp-coffee/tree/feature/tls  
I have tests locally that I have not committed, because getting them to work with travisci will be interesting.  

Here are the new connection options
* `ssl`: false
* `sslOptions` : {} # tls options like cert, key, ca, secureProtocol, passphrase

I like the idea of reconnect core, but that would be a even bigger change, so maybe in the future.

**Comment by AVVS** [comment]
you can use https://github.com/indutny/bud - this might work as a terminator between rabbit and the lib, ie, it might be easier to setup for the tests than do a proper rabbitmq configuration

**Comment by barshow** [comment]
bud compiled openssl when i installed it, that was a negative for me :) I modified the proxy test script to support ssl and got the tests running after a couple trys and fixed some api changes in 0.12

**Comment by mikeatlas** [comment]
How's this coming along? I have an SSL-only Rabbit server listening and am trying to get away from `node-amqp`, but that lib offers the `ssl: { enabled: true }` connection option, and so far I can't seem to get `amqp-coffee` to connect to my server at all without this.

**Comment by barshow** [comment]
https://github.com/dropbox/amqp-coffee/pull/37 is pretty much ready however I dont have a ssl server i use with enough traffic to truly test it.  Its pushed to npm as amqp-coffee@0.1.23-rc4 if you want to give it a try, just pass {ssl: true} into the connection options.  I would love for you to give it a try and then ill merge it through

**Comment by mikeatlas** [comment]
Yes, I'll definitely give it a try. Reason for trying to get away from `node-amqp` package is currently I'm trying to push nearly 50k messages and getting massive memory leaks, others in that thread have pointed here. https://github.com/postwait/node-amqp/issues/383#issuecomment-122698477

**Comment by mikeatlas** [comment]
No luck. Installed `"amqp-coffee": "0.1.23-rc4",` successfully, although (pardon JavaScript and not CoffeeScript example) nothing really seems to happen. I tried to use nearly the exact same connection options (except for your `ssl: true` versus `ssl: {enabled: true }`), and the only console logging I get is my "attempt" message. No other errors are thrown at all, actually. The one thing to note is that I do notice a network handle attempt to be opened with the process monitor, but it closes (rejected, I suppose) rapidly. At least that indicates the library is attempting the connection but probably getting outright rejected?

```javascript
AMQP = require('amqp-coffee');

var connectionOptions = {
  host: process.env.RABBIT_HOST,
  port: process.env.RABBITMQ_PORT,
  login: process.env.RABBITMQ_USER,
  password: process.env.RABBITMQ_PW,
  vhost: process.env.RABBITMQ_VHOST,
  ssl: true
};

console.log("amqp-coffee Connection attempt...");
var amqpConnection = new AMQP(connectionOptions, function(error, amqpConnection) {
  if (error !== null) {
    console.log("amqp-coffee cxn error");
    throw error;
  }
  console.log("amqp-coffee cxn ready");
});

amqpConnection.on('ready', function(){
  console.log("amqp-coffee cxn ready");
});

amqpConnection.on('close', function(){
  console.log("amqp-coffee cxn closed");
});

amqpConnection.on('error', function(error){
  console.log("amqp-coffee cxn error");
  throw error;
});
```

**Comment by barshow** [comment]
@mikeatlas I suspect its failing the ssl handshake for some reason, maybe bad protocols.  try adding sslOptions: {secureProtocol:"TLSv1_method"} to your connection options.  Also you if you can run it with AMQP=3 DEBUG=amqp* you can probably see whats going on.  if not can you paste the output with debugging on. Also what version of node are you running?

**Comment by barshow** [comment]
@mikeatlas actually i think i found the problem, ill post here again when i find the solution

**Comment by barshow** [comment]
@mikeatlas i didnt find the problem, i was just testing the wrong thing.  I can connect to my local rabbit with ssl and to cloudamqp.com ssl amqps server.  

my connection script looks like this.

```coffeescript
amqpClient = new AMQP { ssl: true, host: '**.**.cloudamqp.com', vhost:'**', login:'**', password:'**'}, (error)->
  amqpClient.queue({name:'testQueue'}).declare().bind 'amq.direct','testRoutingKey', ()->
    console.error "working"
```

I would double check your login and pass, if its not correct it fails silently and just attempts to reconnect.

If that still doesn't work, run your script with DEBUG=amqp* AMQP=3 and send me the output.  

Thanks again for you help on this

**Comment by mikeatlas** [comment]
@barshow Sorry for the noise, I also verified against a clean Rabbit `amqps` connection to a test instance on cloudamqp and it appears the problems I'm having connecting over SSL to my own Rabbit instance are isolated from `amqp-coffee`.

**Comment by barshow** [comment]
@mikeatlas no worries, the rabbit logs had good info when I was running into that, usually has something to do with cert paths.  It will boot and launch even with bad paths
