### ISSUE TITLE
UncaughtException: TypeError: Cannot call method 'reset' of undefined

### ISSUE THREAD

**Issue by janajri** [dropbox/amqp-coffee#39]
"version": "0.1.22"

One of our servers crashed recently due to a type error, perhaps caused by a reimplementation of a topology upon reconnection.

**Location:** https://github.com/dropbox/amqp-coffee/blob/master/src/lib/Connection.coffee#L238

**Stack** "uncaughtException: TypeError: Cannot call method 'reset' of undefined\n at /srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/amqp-coffee/bin/src/lib/Connection.js:349:42\n at iterate (/srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/async/lib/async.js:146:13)\n at /srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/async/lib/async.js:157:25\n at /srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/async/lib/async.js:251:17\n at /srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/async/lib/async.js:154:25\n at /srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/async/lib/async.js:248:21\n at /srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/async/lib/async.js:612:34\n at Consumer.Channel._onChannelReconnect (/srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/amqp-coffee/bin/src/lib/Channel.js:190:14)\n at /srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/amqp-coffee/bin/src/lib/Channel.js:107:26\n at /srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/async/lib/async.js:607:21\n at /srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/async/lib/async.js:246:17\n at iterate (/srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/async/lib/async.js:146:13)\n at /srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/async/lib/async.js:157:25\n at /srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/async/lib/async.js:248:21\n at /srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/async/lib/async.js:612:34\n at Consumer.Channel._onChannelMethod (/srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/amqp-coffee/bin/src/lib/Channel.js:330:37)\n at Connection._onMethod (/srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/amqp-coffee/bin/src/lib/Connection.js:602:39)\n at AMQPParser. (/srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/amqp-coffee/bin/src/lib/Connection.js:4:61)\n at AMQPParser.emit (events.js:106:17)\n at AMQPParser.parseMethodFrame (/srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/amqp-coffee/bin/src/lib/AMQPParser.js:111:19)\n at AMQPParser.frameEnd (/srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/amqp-coffee/bin/src/lib/AMQPParser.js:81:16)\n at AMQPParser.frame (/srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/amqp-coffee/bin/src/lib/AMQPParser.js:64:21)\n at AMQPParser.header (/srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/amqp-coffee/bin/src/lib/AMQPParser.js:51:21)\n at AMQPParser.execute (/srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/amqp-coffee/bin/src/lib/AMQPParser.js:31:33)\n at Socket. (/srv/www/inboxmessenger/releases/20150722234551/node_modules/queue-api/node_modules/amqp-coffee/bin/src/lib/Connection.js:426:29)\n at Socket.emit (events.js:95:17)"

**Comment by barshow** [comment]
@janajri thanks for this report.  found a potential problem if you had temporary channels automatically closing between reconnects.  https://github.com/dropbox/amqp-coffee/pull/37 fixes it, its also to published to npm as amqp-coffee@0.1.23-rc5 ill push it to master probably tomorrow

**Comment by janajri** [comment]
@barshow sounds good, glad we could resolve this before the next release.

**Comment by janajri** [comment]
So...it appears we've got some very unexpected behavior occurring here. We've been using  "version": "0.1.23-rc5" however recently got one of these: 

 -  "TypeError: Cannot call method 'reset' of undefined\n at .../node_modules/amqp-coffee/bin/src/lib/Connection.js:418

The codes looks to have compiled correctly: 
 ```

    Connection.prototype._reestablishChannels = function() {
      var _this = this;
      return async.forEachSeries(_.keys(this.channels), function(channel, done) {
        if (channel === "0") {
          return done();
        } else {
          if (_this.channelManager.isChannelClosed[channel]) {
            return done();
          } else {
            return _this.channels[channel].reset(done);
          }
        }
      });
    };
```

Any ideas?

**Comment by janajri** [comment]
I'll try to find a way to reproduce this issue. We're currently using the library to open/close channels at a relatively high rate. We have a bunch of mobile consumers globally that are continually connecting/disconnecting to a rabbit cluster located in a single region. From my understanding it's probably not a good idea to be constantly opening an closing these channels but have not found a better way to handle this just yet.

**Comment by barshow** [comment]
I has to be something around disconnecting & reconnecting a temporary channel where the channel doesn't get fully cleaned up.   https://github.com/dropbox/amqp-coffee/commit/2de31a509813ffcf20b141cd5e3b2655585ac49c will fix it.  Im going to push it up to 0.1.23 once the tests pass

**Comment by barshow** [comment]
published to 0.1.23

**Comment by janajri** [comment]
@barshow thanks again for the quick response. I'll keep you posted if I find a way to reproduce.

**Comment by barshow** [comment]
Sure thing.  It would be awesome to figure out what up with the channel thats causing that.
