### ISSUE TITLE
CHANNEL_ERROR - unexpected method in connection state running

### ISSUE THREAD

**Issue by AVVS** [dropbox/amqp-coffee#44]
Any idea what this means and how it can be fixed? Happens on reconnect attempt

```
12:31:58 arkmail-backend: connected to rabbit@ubuntu72 v3.5.3
12:31:58 arkmail-backend: connection is closed. Had error: { [Error: CHANNEL_ERROR - unexpected method in connection state running] replyCode: undefined }
```

And this would go on infinitely until I restart the process. Thanks for the help

**Comment by AVVS** [comment]
Digging through the logs - it all started with this:

```
connection is closed. Had error: { [Error: CHANNEL_ERROR - unexpected method in connection state running] code: 504 }
```

**Comment by AVVS** [comment]
Anyone can offer an idea why this happens? Loss of connection -> reconnect sequence started and keeps on and on. The same code is used for many other processes and works perfectly well

**Comment by barshow** [comment]
One thing that would help would be turning debugging on to level 3 or higher DEBUG=amqp* AMQP=3 that will print out things it's trying to do and would be super helpful. If you don't want to dig through logs you can email me raw stuff barshow@dropbox.com if you would like. 



—

**Comment by AVVS** [comment]
Added the env vars, so as soon as I get the logs will post them here

**Comment by barshow** [comment]
give amqp-coffee@0.1.25-rc1(https://github.com/dropbox/amqp-coffee/pull/46) a try should fix this for you.  Let me know what happens.  I was able to repro this with your help and have added tests.

**Comment by barshow** [comment]
Hey @AVVS did you have a chance to give it a try?

**Comment by AVVS** [comment]
I did, so far it haven't got stuck yet - which is a really good sign. I'm still keeping an eye on it though, since couple of times it's been a few days without restarts before this occurred. Overall looks great

**Comment by barshow** [comment]
I think ill let it sit in this pr for another week, just in case.  Thanks for you help on this!

**Comment by AVVS** [comment]
I can confirm that this works well, 20 days - no problems
