### ISSUE TITLE
Handle method.basicCancel

### ISSUE THREAD

**Issue by AVVS** [dropbox/amqp-coffee#52]
When we have the following options and #51 is merged in consumer gets new events

```js
{
      host: 'localhost',
      port: 5672,
      login: 'guest',
      password: 'guest',
      vhost: '/',
      temporaryChannelTimeout: 6000,
      clientProperties: {
        capabilities: {
          consumer_cancel_notify: true,
        },
      },
},
```

Example log:

```js
  amqp:AMQPParser 2 > method basicCancel {"consumerTag":"Vitalys-iMac.local-30767-1452811088079","noWait":1} +20s
  amqp:Consumer onMethod basicCancel, {"consumerTag":"Vitalys-iMac.local-30767-1452811088079","noWait":1} +1ms
```

It would be nice to have  https://github.com/dropbox/amqp-coffee/blob/master/src/lib/Consumer.coffee#L196 extended with a handler for such an event (https://www.rabbitmq.com/consumer-cancel.html). It could simply emit an event, which a user must handle, or automatically try to reconnect. To synthetically generate such an event - create a consumer and then purge queue/exchange in the rabbitmq management console

**Comment by barshow** [comment]
What would you want it to do? I suppose emitting an error on the consumer could work?

**Comment by AVVS** [comment]
Maybe another kind or event such as 'cancel'? Error would, of course, work, but then we'll have to choose error code, structure it similarly to rabbitmq response, and this is likely undesirable

**Comment by barshow** [comment]
yeah, i really hate adding random emitters, everything but errors are callback based.  I think ill add the cancel listener and fall back to error if there isn't a cancel listener.
