### ISSUE TITLE
working with activeMQ?

### ISSUE THREAD

**Issue by andreas-polz** [dropbox/amqp-coffee#57]
Has anyone tried to make this work with activeMQ instead of rabbit?
according to docs it should click, and my activeMQ instance is configured with:
`<transportConnector name="amqp" uri="amqp://0.0.0.0:5672?maximumConnections=1000&amp;wireformat.maxFrameSize=104857600"/>`

yet, if i try to run the basic.coffee from the examples (with port 5672 added), it just hangs around and i don´t see it appear as a consumer in my activemq or do anything useful until i kill it again.

amazon gift code or pizza vouchers on offer for any helpful pointers!

best regards
   Andreas

**Comment by barshow** [comment]
I'm looking into this, so far it looks like we're not interpreting a header packet correctly, or its sending it wrong.  Ill keep looking around

**Comment by barshow** [comment]
activeMQ is amqp 1.0.0 amqp-coffee only supports 0.9.1 right now. 1.0.0 is fairly new and not very widely adopted yet.  However it would be nice to have a better error message.  So ill work on that.
