### ISSUE TITLE
support for exchange to exchange routing

### ISSUE THREAD

**Issue by trickpattyFH20** [dropbox/amqp-coffee#58]
Can't seem to find anything in the code or the documentation about exchange to exchange routing, as described here: https://www.rabbitmq.com/e2e.html

Are there plans to implement this feature or would there be room for a contribution here?

**Comment by barshow** [comment]
https://github.com/dropbox/amqp-coffee/pull/59

I added e2e bindings / unbinding to that pull request.

you can `npm install amqp-coffee@0.1.28-rc1` to test it out.  Let me know if that works for you!
