### ISSUE TITLE
Performing a Connection Healthcheck

### ISSUE THREAD

**Issue by MarkHerhold** [dropbox/amqp-coffee#66]
Hi, I'd like to determine if a/all of the currently established connections to RabbitMQ are healthy to help assess the overall health of my application periodically. Can you give a recommendation to doing this?

One thought I had would be to use the existing client, kick off a heartbeat and listen for the response. However, I don't know how this would affect the `amqp-coffee` internals given that `amqp-coffee` would be performing its own healthchecks. Thoughts?

Awesome module by the way! :heart_eyes:

**Comment by barshow** [comment]
Thanks Mark!

You can check .state on your main amqp connection.  You can also tweak the heartbeat option if you want a more frequent check. The default now is every 10 seconds.  We only ever make one connection so if that connection fails all channels will disconnect.  So checking the connection health should be adequate.  You can also listen for a 'close' or 'error' event.

Good Luck!
