### ISSUE TITLE
node-uuid -> uuid, pin versions for deps

### ISSUE THREAD

**Issue by AVVS** [dropbox/amqp-coffee#71]
Hi, can you do what the subject is describing? 👍

**Comment by MarkHerhold** [comment]
Related (node-uuid --> uuid): https://github.com/dropbox/amqp-coffee/pull/69

**Comment by barshow** [comment]
Done and done!

**Comment by AVVS** [comment]
@barshow can you publish the new version of the pkg? thx :)

**Comment by barshow** [comment]
ahh yes 0.1.29 published
