### ISSUE TITLE
Channels not closing

### ISSUE THREAD

**Issue by testower** [dropbox/amqp-coffee#9]
I have a problem with channels not closing. When using node-amqp I had the same issue, but resolved it with this queue option:

closeChannelOnUnsubscribe: true

Then when my socket.io client disconnected I would unsubscribe his consumerTag from the queue, and the channel would close:

``` javascript
socket.on('disconnect', function () {
    if (consumerTag) {
        my_queue.unsubscribe(consumerTag);
    }
});
```

Would there be an equivalent in amqp-coffee?

I'm trying all sorts of things like queue.channel.close(), consumer.cancel() and queue.delete(), but none seem to close the channels. I can see that they remain in rabbitmq dashboard with no consumer.

**Comment by trickpattyFH20** [comment]
@testower @barshow just reading through this issue and curious about scaling this pattern.

Is it an OK / good practice to start a new consumer on the connect event for each websocket, then store that consumer somewhere in memory and finally call `.close()` on that consumer on the `socket.disconnect` event?

**Comment by barshow** [comment]
depends on if you're using a shared queue for each consumer or if your setting up and tearing down queues.  Setting up and tearing down queues is a expensive things an should only be done when necessary.  If you're just connecting a consumer thats a fairly lightweight operation so without know more about your infra and what your doing I would say its ok.  

Let me know if you want a more specific answer :)
